rem 更新odoo为本翻译
xcopy .\source\odoo  d:\odoo13-x64\source\odoo /E /Y
xcopy .\source\addons  d:\odoo13-x64\source\odoo\addons /E /Y

rem 企业版

xcopy .\source_ent  d:\pjweb\o13.erpapp.cn\addons_ent /E /Y
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\.tx

rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\account_taxcloud
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_ae
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_ar
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_ar_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_at
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_at_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_au
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_au_aba
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_au_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_be
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_be_coda
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_be_hr_payroll
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_be_hr_payroll_account
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_be_hr_payroll_fleet
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_be_intrastat
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_be_intrastat_2019
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_be_invoice_bba
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_be_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_bo
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_bo_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_br
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_br_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_ca
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_ca_check_printing
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_ch
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_ch_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_cl
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_cl_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_co
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_co_edi
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_co_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_cr
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_de
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_de_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_de_skr03
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_de_skr04
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_do
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_do_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_ec
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_es
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_es_real_estates
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_es_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_et
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_et_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_eu_service
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_fr
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_fr_certification
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_fr_fec
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_fr_hr_payroll
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_fr_pos_cert
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_fr_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_fr_sale_closing
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_generic_coa
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_gr
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_gr_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_gt
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_hk
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_hn
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_hr
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_hr_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_hu
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_hu_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_in
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_in_hr_payroll
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_in_purchase
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_in_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_in_sale
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_in_schedule6
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_in_stock
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_it
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_jp
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_jp_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_lu
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_lu_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_lu_reports_electronic
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_ma
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_ma_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_mx
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_mx_edi
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_mx_edi_customs
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_mx_edi_external_trade
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_mx_edi_landing
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_mx_edi_payment
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_mx_edi_payment_bank
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_mx_edi_sale_coupon
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_mx_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_mx_reports_closing
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_mx_tax_cash_basis
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_nl
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_nl_intrastat
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_nl_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_no
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_no_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_nz
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_pa
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_pe
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_pl
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_pl_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_pt
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_ro
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_ro_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_sa
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_sg
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_sg_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_si
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_si_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_syscohada
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_th
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_th_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_tr
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_uk
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_uk_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_us
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_us_check_printing
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_us_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_uk_reports_hmrc
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_uy
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_uy_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_ve
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_vn
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\l10n_vn_reports
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\sale_account_taxcloud
rd /s/q d:\pjweb\o13.erpapp.cn\addons_ent\website_sale_account_taxcloud
